# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: airsoft MadMaxista
email: airsoftmadmaxista@protonmail.com
description: >
  Bitácora políticamente incorrecta; <br>
  La vía frugal y sana de esto de las bolicas y las batallitas de mentira. <br>
  Feliz aquel que no rinde a la usura vasallaje.
tagline: vitam impendere vero
location: Huesca (Aragón) [España]
date: true
baseurl: "/airsoftmadmaxista.github.io" # the subpath of your site, e.g. /blog
url: "http://airsoftmadmaxista.github.io" # the base hostname & protocol for your site, e.g. http://example.com
author: DespertaFerro
google_analytics:

# SEO
twitter:
  username:

logo: /assets/logo.png

lang: es

facebook:
 app_id:

social:
  name: DespertaFerro
  links:
    - https://twitter.com/jdatap
    - https://www.linkedin.com/in/johncoene
    - https://plus.google.com/109009224717674019651
    - https://github.com/JohnCoene

# Build settings
exclude: README.md
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
plugins_dir:
  - jekyll-roman
  - jekyll-seo-tag
